#!/bin/bash

die() { echo $1; exit 1; }

[[ $# -eq 0 ]] && die "No arguments given"
[[ ! -a $1 ]] && die "'$1' doesn't exist"

currdir=`dirname $0`

process_file() {
    jackfile=$1
    xmlfile=${1/.jack/.xml}
    ./Main.rb $jackfile > $xmlfile
}

if [ -d $1 ]; then
    for file in $1/*.jack; do process_file $file; done
else
    process_file $1
fi
