from Parser import Parser

def test_01():
  with open("./max/Max.asm", 'r') as input_file:
    parser = Parser(input_file)

    print(parser.current_command)
    print(parser.dest())
    print(parser.comp())
    print(parser.jump())
    parser.advance()
    print("========")
    print(parser.current_command)
    print(parser.dest())
    print(parser.comp())
    print(parser.jump())
    parser.advance()
    print("========")
    print(parser.current_command)
    print(parser.dest())
    print(parser.comp())
    print(parser.jump())
    parser.advance()
    print("========")
    print(parser.current_command)
    print(parser.dest())
    print(parser.comp())
    print(parser.jump())
    parser.advance()
    print("========")
    print(parser.current_command)
    print(parser.dest())
    print(parser.comp())
    print(parser.jump())
    parser.advance()
    print("========")
    print(parser.current_command)
    print(parser.dest())
    print(parser.comp())
    print(parser.jump())

if __name__ == "__main__":
  test_01()